### ISSUE TITLE
Doesn't build on xcode 10.2 due to various path issues

### ISSUE THREAD

**Issue by manysounds** [AudioKit/Playgrounds#5]
On Mojave
Fresh install of XCode

Showing Recent Messages
:-1: ~~~~~/Xcode/Playgrounds-master/Xcode/Pods/Target Support Files/Pods-AudioKitPlaygrounds/Pods-AudioKitPlaygrounds.debug.xcconfig: unable to open file (in target "AudioKitPlaygrounds" in project "AudioKitPlaygrounds") (in target 'AudioKitPlaygrounds')

**Comment by bashirsk** [comment]
I'm having the same issue

**Comment by cadyfatcat** [comment]
Also having this issue

**Comment by aure** [comment]
It was stuck on an old version of AudioKit, allowing it to update works on my machine.  I pushed up a pod file fix.

**Comment by ghost** [comment]
I have this issue on the last version. 

From terminal:
```
Using AudioKit (4.7.1)
```

**Comment by aure** [comment]
Should be already on 4.7.2, but I think even 4.7.1 should work. I'm happy to screen share with you, but I can't help with such limited info.

**Comment by coughski** [comment]
I’m still seeing this issue in Xcode 10.2.1. Are we supposed to run “pod install” ourselves outside of Xcode?

**Comment by Engid** [comment]
> I’m still seeing this issue in Xcode 10.2.1. Are we supposed to run “pod install” ourselves outside of Xcode?

Hey I was having issues too but this newer release worked for me: https://github.com/AudioKit/AudioKit/releases/tag/v4.7.2
